### ISSUE TITLE
Goal Reward is ignored

### ISSUE THREAD

**Issue by StrongJoshua** [svpino/cs7641-assignment4#1]
![image](https://user-images.githubusercontent.com/6654606/39098353-8fefe7f4-4637-11e8-93c7-daa4b6c10651.png)
No matter what I set the goal reward to, it remains at 0 for intents and purposes. I even tried making the goal reward negative, as can be seen in the image, but the policy still targets the goal, no matter what.

**Comment by svpino** [comment]
Yup, this is not an issue. The algorithm targets the goal state regardless of the specific reward that you attach to it.
